server:
  port: 8713

spring:
  rabbitmq:
    addresses: localhost:5672
    username: jjy
    password: 123
    virtual-host: /jjy
    connection-timeout: 500

    # 生产者的配置
    template:
      retry:
        enabled: true # 开启超时重试机制
        initial-interval: 1000ms # 失败后的初始等待时间
        multiplier: 1 # 失败后下次的等待时长倍数，下次等待时长 = initial-interval * multiplier
        max-attempts: 3 # 最大重试次数
    publisher-confirm-type: none # 开启publisher confirm机制，并设置confirm类型
    publisher-returns: false # 开启publisher return机制

    # 消费者的配置
    listener:
      simple:
        prefetch: 1000
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 1000ms # 初识的失败等待时长为1秒
          multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
          max-attempts: 3 # 最大重试次数
          stateless: true # true无状态；false有状态。如果业务中包含事务，这里改为false



