server:
  port: 8704

spring:
  application:
    name: open-feign-consumer
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
        username: nacos
        password: nacos
    sentinel:
      transport:
        dashboard: localhost:8858
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true